export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/person1.jpeg",
    username: "Aron Yipeekayay",
  },
  {
    id: 2,
    profilePicture: "assets/person/person2.JPG",
    username: "Cupid Jay",
  },
  {
    id: 3,
    profilePicture: "assets/person/person3.jpeg",
    username: "Gin Dojima",
  },
  {
    id: 4,
    profilePicture: "assets/person/person4.PNG",
    username: "J Waris",
  },
  {
    id: 5,
    profilePicture: "assets/person/person5.jpeg",
    username: "Lalisa Manoban",
  },
  {
    id: 6,
    profilePicture: "assets/person/person6.jpeg",
    username: "Kim Jennie",
  },
  {
    id: 7,
    profilePicture: "assets/person/person7.jpg",
    username: "Mimi Bennet",
  },
  {
    id: 8,
    profilePicture: "assets/person/person8.jpeg",
    username: "Kristine Thomas",
  },
  {
    id: 9,
    profilePicture: "assets/person/person9.jpeg",
    username: "Jane Woods",
  },
  {
    id: 10,
    profilePicture: "assets/person/person10.jpg",
    username: "Sofie Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I’m grateful to every moment of my life because it brought me here with you 👩🏼‍❤️‍👨🏻",
    photo: "assets/post/post1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "#BlackLivesMatter",
    photo: "assets/post/post2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "This place makes me want to change my address 😃",
    photo: "assets/post/post3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "some baking idea",
    photo: "assets/post/post4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/post5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/post6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "good food, good mood 🥰",
    photo: "assets/post/post7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "📍Espa Life at Corinthia. With my girls 💕 ",
    photo: "assets/post/post8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Under the sea 🌊",
    photo: "assets/post/post9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/post10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
